// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/openshift-cloud-functions/tektoncd-operator/pkg/apis/tekton/v1alpha1.Install":       schema_pkg_apis_tekton_v1alpha1_Install(ref),
		"github.com/openshift-cloud-functions/tektoncd-operator/pkg/apis/tekton/v1alpha1.InstallSpec":   schema_pkg_apis_tekton_v1alpha1_InstallSpec(ref),
		"github.com/openshift-cloud-functions/tektoncd-operator/pkg/apis/tekton/v1alpha1.InstallStatus": schema_pkg_apis_tekton_v1alpha1_InstallStatus(ref),
	}
}

func schema_pkg_apis_tekton_v1alpha1_Install(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Install is the Schema for the installs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift-cloud-functions/tektoncd-operator/pkg/apis/tekton/v1alpha1.InstallSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift-cloud-functions/tektoncd-operator/pkg/apis/tekton/v1alpha1.InstallStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/openshift-cloud-functions/tektoncd-operator/pkg/apis/tekton/v1alpha1.InstallSpec", "github.com/openshift-cloud-functions/tektoncd-operator/pkg/apis/tekton/v1alpha1.InstallStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tekton_v1alpha1_InstallSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "InstallSpec defines the desired state of Install",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tekton_v1alpha1_InstallStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "InstallStatus defines the observed state of Install",
				Properties: map[string]spec.Schema{
					"resources": {
						SchemaProps: spec.SchemaProps{
							Description: "The resources applied",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"version": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"resources", "version"},
			},
		},
		Dependencies: []string{},
	}
}
