---
apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: simple-pipeline
spec:
  targetResource:
    apiVersion: tekton.dev/v1beta1
    kind: Pipeline
  title: simple-pipeline
  description: An example of simple pipeline
  snippet: false
  yaml: |
    apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      name: simple-pipeline
    spec:
      params:
        - name: PARAM_NAME
          type: string
          default: defaultValue
      resources:
        - name: app-source
          type: git
        - name: app-image
          type: image
      tasks:
        - name: first-task
          taskRef:
            name: task-name
          resources:
            inputs:
              - name: source
                resource: app-source
            outputs:
              - name: image
                resource: app-image
          params:
            - name: PARAM
              value: $(params.PARAM_NAME)
