FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:latest

LABEL com.redhat.delivery.appregistry=true

ENV OPERATOR=/usr/local/bin/openshift-pipelines-operator \
    USER_UID=1001 \
    USER_NAME=openshift-pipelines-operator

ENV LANG=en_US.utf8

# install operator binary
COPY operator ${OPERATOR}

COPY build/bin /usr/local/bin
RUN  /usr/local/bin/user_setup

COPY deploy/resources /deploy/resources

ENTRYPOINT ["/usr/local/bin/entrypoint"]

USER ${USER_UID}
